version: "3"

services:
  client:
    container_name: ffinance_client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - ffinance_network

  server:
    container_name: ffinance_server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - ffinance_network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=ffinance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - ffinance_network

networks:
  ffinance_network:
    external: true
